### ISSUE TITLE
 Cannot set property '$id' of undefined

### ISSUE THREAD

**Issue by mid787** [mrajcok/angularjs-periscope#1]
Hi. 

I've managed to test and see the built in examples and also my custom code changing app.html and app.js.

But looking at this simple [**plunker**](http://plnkr.co/edit/yKfJaAXUrL9udRj7WXpU?p=preview) (<sub> from NG-docs </sub>)
- When I click the `Peri$scope` button  - there is an [**error**](http://i.imgur.com/4R2hOZD.png) :

> TypeError: Cannot set property '$id' of undefined
>     at http://localhost:3000/scripts/periscopeModule.js:722:35
>     at Array.forEach (native)
>     at Object.periscopeService.addObjectProperties (http://localhost:3000/scripts/periscopeModule.js:646:15)
>     at http://localhost:3000/scripts/periscopeModule.js:938:28
>     at Array.forEach (native)
>     at Scope.$scope.periscope (http://localhost:3000/scripts/periscopeModule.js:859:16)
>     at fn (eval at <anonymous> (http://localhost:3000/bower_components/angularjs-> 1.4/angular.js:13365:15), <anonymous>:4:218)
>     at callback (http://localhost:3000/bower_components/angularjs-1.4/angular.js:23613:17)
>     at Scope.$eval (http://localhost:3000/bower_components/angularjs-1.4/angular.js:16052:28)
>     at Scope.$apply (http://localhost:3000/bower_components/angularjs-1.4/angular.js:16152:25)

The flow is like [this](http://i.imgur.com/sQrOqpI.png)

But If i change the `select` method's name

```
 $scope.select = function(pane) {
           angular.forEach(panes, function(pane) {
             pane.selected = false;
           });
           pane.selected = true;
         };
```

To a different name (say `select2`) , then I **do** see a [graph](http://i.imgur.com/2YpNfBN.png) - but now it says ( obviosly) That it can't find the method.

Am I doing something wrong ? 

Related info : 

These are the exact [**App.js and App.html**](http://jsbin.com/muveduluka/1/edit?html,js) files i'm using under node.

**Comment by mrajcok** [comment]
Although the program will no longer crash with the change I just made, the scopes in the panes array do not properly reference (point to) scopes 5 and 7 in the diagram (like the pane properties in scopes 11 and 12 do).  It is a pretty complicated diagram that gets generated:
![1449954006869_1](https://cloud.githubusercontent.com/assets/182257/11763863/873fc6c4-a0e9-11e5-98a9-a7dfbe9e6413.png)

I'm probably not going to try and make this work any better than what you see above.

**Comment by mid787** [comment]
Thank you . Will it be ok to post further issues if i encounter with ...?

**Comment by mrajcok** [comment]
Sure, but as you experienced, it might take a while for me to get around to them.

**Comment by mid787** [comment]
Mark , btw - I was thinking to make this tool an online tool like jsfiddle/plunker.(with your permission of course) and i'll be happy to further discuss about  its design/features  ( if you are interested) via email.( at my profile). I'm an experienced  server/client /db programmer.
