### ISSUE TITLE
Free ng-conf ticket

### ISSUE THREAD

**Issue by aaronfrost** [mrajcok/angularjs-periscope#2]
@mrajcok I am one of the ng-conf organizers. I noticed that you are the alltime highest ranking person on StackOverflow for answering questions with the "angularjs" tag. Me and the other ng-conf organizers would like to offer you a free ticket to the event. We definitely think that you need to be there. If you can get the airfare and hotel, and would love for you to be at the event. Please let me know if you can take advantage of this. 

And thanks for all that you have done for the entire Angular community.

**Comment by aaronfrost** [comment]
https://twitter.com/js_dev/status/704566915407040512

**Comment by alexcastillo** [comment]
+1

**Comment by Trendy** [comment]
+1!!!

**Comment by mrajcok** [comment]
I told Aaron I will attend.  I'm looking forward to it.
